# .streamlit/secrets.toml

# Gemini API Key (for Gemini 2.0 Flash sentiment analysis)
GEMINI_API_KEY = "AIzaSyAbCkUgwtNO0-kSjR3Izi0nuPuusP7ViK8"

# Slack Incoming Webhook URL (for rich alerts)
SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/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"

# Alpha Vantage API Key (for enriched news sentiment & fundamentals)
ALPHA_VANTAGE_API_KEY = "SRXT6Y1HWY06QSLC"